[package]
name = "botticelli_interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Trait definitions for the Botticelli LLM API library"
keywords.workspace = true
categories.workspace = true

[dependencies]
# workspace
botticelli_core.workspace = true
botticelli_error.workspace = true
botticelli_rate_limit.workspace = true
botticelli_storage.workspace = true

# external
async-trait.workspace = true
elicit_db.workspace = true
chrono.workspace = true
derive_builder.workspace = true
derive-getters.workspace = true
derive-new.workspace = true
derive_setters.workspace = true
derive_more.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tracing.workspace = true
uuid.workspace = true
