//! MCP tool implementations organized by category.

mod core;
mod discord;
mod elicitation;
mod execution;
mod narrative;
mod scene;

use crate::rmcp_server::BotticelliServer;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::tool_router;

/// Get the tool router for BotticelliServer (must be public for server.rs).
///
/// This function provides access to the tool_router() method generated by #[tool_router].
#[tracing::instrument]
pub(super) fn get_tool_router() -> ToolRouter<BotticelliServer> {
    BotticelliServer::tool_router()
}

// Empty impl block required for #[tool_router] macro
impl BotticelliServer {}

// This macro gathers all tool methods from the separate module files
#[tool_router]
impl BotticelliServer {}
